---
title: "Untitled"
output: html_document
date: '2023-06-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
install.packages("plotrix")
install.packages("ggh4x")
library(plotrix)
library(ggplot2)
library(lubridate)

```


```{r, warning=FALSE}
library(readxl)

Monthly_Data <- read_excel("Project 2 Historical Data.xlsx", 
    sheet = "60-40 Returns Monthly", range = "B10:D1174")

for(i in 0:100){
  Monthly_Data[paste0("Alpha(Large Cap %) = ", i)] = NA
  }

for(i in 0:100){
  alpha = i/100
  for(j in 1:1164){
    Monthly_Data[j,i+4]= (alpha*Monthly_Data$`Large Cap TR`[j]) + ((1-alpha)*Monthly_Data$FIXED[j])}}


month_12 = data.frame(matrix(ncol=3, nrow=1153))
colnames(month_12) = c("Date", "LC_mult", "Fixed_mult")
month_12$Date = Monthly_Data$Date[1:1153]

for(i in 1:1153){
  mult1 = 1
  mult2 = 1
  x = 1
  while(x <= 12){
    mult1 = mult1 * (1 + Monthly_Data$`Large Cap TR`[i+x-1])
    mult2 = mult2 * (1 + Monthly_Data$FIXED[i+x-1])
    x = x + 1}
  month_12$LC_mult[i] = -(1 - mult1)
  month_12$Fixed_mult[i] = -(1 - mult2)}
```

```{r}
Monthly = data.frame(matrix(ncol=3, nrow=1153))
colnames(Monthly) = c("Date", "LCTR", "FIXED_TR")
Monthly$Date = month_12$Date
Monthly$LCTR = month_12$LC_mult
Monthly$FIXED_TR = month_12$Fixed_mult
for(i in 0:100){
  Monthly[paste0("Alpha", i)] = NA
  }


for(i in 0:100){
  alpha = i/100
  for(j in 1:1153){
    Monthly[j,i+4]= (alpha*Monthly$LCTR[j]) + ((1-alpha)*Monthly$FIXED_TR[j])}}


Alpha = data.frame(matrix(nrow=101, ncol=5))
colnames(Alpha) = c("Spread_Ratio", "min", "max", "Mean", "STD_DEV") 
Alpha$Spread_Ratio = colnames(Monthly)[4:104]


for(i in 1:101){
    Alpha[i, 2] = min(Monthly[, i+3])
    Alpha[i, 3] = max(Monthly[, i+3])
    Alpha[i, 4] = sum(Monthly[,i+3])
    Alpha[i, 4] = Alpha[i, 4]/1153
    Alpha[i, 5] = sqrt(var(Monthly[, i+3]))}


sig_loss1 = qnorm(0.05, mean = mean(Monthly$Alpha60), sd = sqrt(var(Monthly$Alpha60)), lower.tail = TRUE)
sig_loss2 = qnorm(0.01, mean = mean(Monthly$Alpha60), sd = sqrt(var(Monthly$Alpha60)), lower.tail = TRUE)
sig_loss3 = qnorm(0.001, mean = mean(Monthly$Alpha60), sd = sqrt(var(Monthly$Alpha60)), lower.tail = TRUE)
sig_loss4 = qnorm(0.0001, mean = mean(Monthly$Alpha60), sd = sqrt(var(Monthly$Alpha60)), lower.tail = TRUE)

significant_losses = subset(Monthly, Monthly$Alpha60 <= sig_loss1)[c("Date", "Alpha60")]
require(zoo)
significant_losses["Year"] <- year(significant_losses$Date)
significant_losses["Month"] = months(significant_losses$Date)
significant_losses$Month <- factor(significant_losses$Month, levels = rev(month.name))
significant_losses$Year <- factor(significant_losses$Year, levels = unique(year(significant_losses$Date)))
significant_losses["Probability"] = NA

for(i in 1:54){
  if(significant_losses$Alpha60[i] < sig_loss1){
    significant_losses$Probability[i] = "< 5%"}
  if(significant_losses$Alpha60[i] < sig_loss2){
    significant_losses$Probability[i] = "< 1%"}
  if(significant_losses$Alpha60[i] < sig_loss3){
    significant_losses$Probability[i] = "< 0.1%"}
  if(significant_losses$Alpha60[i] < sig_loss4){
    significant_losses$Probability[i] = "< 0.01%"}}

significant_losses$Probability <- factor(significant_losses$Probability, levels = c("< 5%", "< 1%", "< 0.1%", "< 0.01%"))


scales_x <- list(
  c(`1936`, `1974`, `2022`) = scale_x_continuous(limits = c(0, 0.2), breaks = seq(5, 25, 5)),
  `f` = scale_y_continuous(limits = c(0, 40), breaks = seq(0, 40, 10)),
  `r` = scale_y_continuous(limits = c(10, 20), breaks = seq(10, 20, 2))


significant_losses %>%
  ggplot()+
  geom_col(aes(x=abs(Alpha60), y = Month, fill = Probability)) +
  scale_x_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5)) +
  facet_wrap(~as.character(Year)) +
  labs(title="12-Month Significant Losses on the 60-40 Portfolio",
  x = "Total Loss on Returns")+
  scale_fill_manual(values  = c("< 5%" = "yellow",
                                "< 1%" = "orange",
                                "< 0.1%" = "orangered1",
                                "< 0.01%" = "red2")) +
  geom_text(aes(x = abs(Alpha60), y = Month, label = round(Alpha60, 4)), hjust=1) +
  theme(strip.text = element_text(size = 15),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        title =element_text(size=18, face='bold'),
        legend.text = element_text(size = 12)) +
  ggh4x::force_panelsizes(rows = NULL, cols = NULL, respect = NULL)

significant_losses[1:26,] %>%
  group_by(Year, Month) %>%
  ggplot()+
  labs(title="Compounded 12-Month Significant Losses of the 60-40 Portfolio",
  subtitle = "1929-1936",
       x = "Total Loss on Returns")+
  geom_col(aes(x = Alpha60, fill = Month),)+
  facet_wrap(~Year) +
  ylim(0,-0.3))
```

```{r}
Annual60 = subset(Monthly, months(Monthly$Date) == "January")[c("Date", "Alpha60")]
colnames(Annual60) = c("Date", "TR")

Monthly60 = Monthly[c("Date", "Alpha60")]
colnames(Monthly60) = c("Date", "TR")


for(i in 1:1153){
  if(Monthly60$Alpha60[i] < -0.225){
    Monthly60$line_color[i] = "red"}
  if(Monthly60$Alpha60[i] > -0.225 & Monthly60$Alpha60[i] < -0.075){
    Monthly60$line_color[i] = "redorange"}
  if(Monthly60$Alpha60[i] > -0.075 & Monthly60$Alpha60[i] < 0.075){
    Monthly60$line_color[i] = "orange"}
  if(Monthly60$Alpha60[i] > 0.075 & Monthly60$Alpha60[i] < 0.225){
    Monthly60$line_color[i] = "yelloworange"}
  if(Monthly60$Alpha60[i] > 0.225 & Monthly60$Alpha60[i] < 0.3){
    Monthly60$line_color[i] = "yellow"}
  if(Monthly60$Alpha60[i] > 0.3){
    Monthly60$line_color[i] = "green"}}

Annual60 <- Annual60 %>%
  mutate("Date" = year(Annual60$Date))



line_color <- as.factor(c("1", "2", "3", "4", "5", "6", "7"))
TR = Annual60$TR
line_color[TR < -0.2] <- 1
line_color[TR > -0.2 & TR < -0.1] <- 2
line_color[TR > -0.1 & TR < 0] <- 3
line_color[TR > 0 & TR < 0.1] <- 4
line_color[TR > 0.1 & TR < 0.2] <- 5
line_color[TR > 0.2 & TR < 0.3] <- 6
line_color[TR > 0.3] <- 7
Annual60["line_color"] <- line_color


for(i in 1:97){
  if(Annual60$Alpha60[i] < -0.2){
    Annual60$line_color[i] = "red4"}
  if(Annual60$Alpha60[i] > -0.2 & Annual60$Alpha60[i] < -0.1){
    Annual60$line_color[i] = "redorange"}
  if(Annual60$Alpha60[i] > -0.1 & Annual60$Alpha60[i] < 0){
    Annual60$line_color[i] = "orange"}
  if(Annual60$Alpha60[i] > 0 & Annual60$Alpha60[i] < 0.1){
    Annual60$line_color[i] = "goldenrod1"}
  if(Annual60$Alpha60[i] > 0.1 & Annual60$Alpha60[i] < 0.2){
    Annual60$line_color[i] = "yellow"}
  if(Annual60$Alpha60[i] > 0.2 & Annual60$Alpha60[i] < 0.3){
    Annual60$line_color[i] = "greenyellow"}
  if(Annual60$Alpha60[i] > 0.3){
    Annual60$line_color[i] = "green"}}

library(lubridate)

ggplot2::ggplot(data = Annual60, aes(x=Date, y = Alpha60, color = line_color)) + geom_line(aes(group = 1)) + geom_point(data = Annual60, aes(x=Date, y = Alpha60, color = line_color)) + ylim(-0.3, 0.4)

Annual60 <- Annual60 %>%
  mutate(line_color = c(factor(Annual60$line_color)))


ggplot(data = Annual60, aes(x=Date, y = Alpha60, color = line_color)) + geom_line(data = Annual60, aes(color = c(Alpha60 < -0.225, Alpha60 > -0.225 & Alpha60 < -0.075)))+ geom_point(data = Annual60, aes(color = c(Alpha60 < -0.225, Alpha60 > -0.225 & Alpha60 < -0.075))) + ylim(-0.3, 0.4)

plot(x=Annual60$Date, y=Annual60$Alpha60, col = Annual60$line_color)



myPlot = function(y, x,
    colors=c("blue","red"),
    xlab=deparse(substitute(x)),
    ylab=deparse(substitute(y)), ...)
{
    n = length(x)
    y.pos = y.neg = y
    y.pos[y<0] = 0
    y.neg[y>0] = 0
    plot(y~x, type="n", xlab=xlab, ylab=ylab, ...)
    grid()
    polygon(c(x[1],x,x[n]),c(0,y.pos,0),col=colors[1],border=NA)
    polygon(c(x[1],x,x[n]),c(0,y.neg,0),col=colors[2],border=NA)}

myPlot(x = Annual60$Date, y = Annual60$Alpha60)

ggplot2::ggplot(data = Annual60, aes(x=Date, y = Alpha60, color = line_color)) + geom_line(aes(group = 1)) + geom_point(data = Annual60, aes(x=Date, y = Alpha60, color = line_color)) + ylim(-0.3, 0.4)

A = 
plot(A~y2, data, type="h", lwd=2, col=c("blue","red")[1+(A<0)],xlab="Year")


install.packages("RColorBrewer")
library(RColorBrewer)
my_colors = brewer.pal(7, "Set2") 

clplot(x=(Monthly$Date), y=Monthly$Alpha60, main="", lwd=1, levels=c(-0.3, -0.15, 0, 0.15, 0.30, 0.45, 0.6), col=my_colors, showcuts=T , bty="n", ylim=c(-0.5,0.6))

my_colors = c("red4", "orangered2", "yellow", "green", "blue")
clplot(x=Annual60$Date, y=Annual60$Alpha60, main="", lwd=1, levels=c(-0.225, -0.075, 0.075, 0.225, 0.30), col=my_colors, showcuts=F , bty="n", ylim=c(-0.3,0.4), xlim = c(1925, 2025), xlab="Year", ylab="Total Return", title(main = "Annual 60/40 Total Returns"))


for(i in 0:100){
  alpha = i/100
  for(j in 1:1153){
    Monthly[j,i+4]= alpha*Monthly$LCTR[j] + (1-alpha)*Monthly$FIXED_TR[j]}}

plot(xlab= "Alpha", x = 0:10 0, ylab="Total Return", y= Monthly[1153, 4:104], main = "All 2022 Total Returns", par(lty = 1))
```

```{r}
Alpha = data.frame(matrix(nrow=101, ncol=6))
colnames(Alpha) = c("Spread_Ratio", "min", "max", "Mean", "STD_DEV", "Std_29") 
Alpha$Spread_Ratio = colnames(data)[4:104]


for(i in 1:length(Alpha$Spread_Ratio)){
    Alpha[i, 2] = min(data[, i+3])
    Alpha[i, 3] = max(data[, i+3])
    Alpha[i, 4] = sum(data[,i+3])
    Alpha[i, 4] = Alpha[i, 4]/97
    Alpha[i, 5] = sqrt(var(data[, i+3]))
    Alpha[i, 6] = sqrt(var(data[29:97, i+3]))}


Returns_30yr = c(2.755,
2.954166667,
3.0975,
3.443333333,
3.4825,
4.078333333,
4.119166667,
3.941666667,
4.055,
4.073333333,
4.186666667,
4.223333333,
4.694166667,
4.9,
5.345833333,
6.1725,
6.734166667,
5.998333333,
5.796666667,
6.9875,
7.983333333,
8.213333333,
7.944166667,
7.725,
8.544166667,
9.316666667,
11.43333333,
13.56333333,
12.66333333,
11.25583333,
12.43333333,
10.70333333,
7.69,
8.609166667,
8.936666667,
8.401666667,
8.619166667,
8.085,
7.675,
6.579166667,
7.409166667,
6.8075,
6.723333333,
6.5675,
5.531666667,
5.913333333,
5.88,
5.4675,
5.405833333,
5.0325,
5.1,
4.520833333,
4.873333333,
4.796666667,
4.218333333,
4.095,
4.180833333,
3.884166667,
2.8825,
3.459166667,
3.269166667,
2.818333333,
2.58,
2.886666667,
3.095,
2.525,
1.51,
2.0475,
3.161666667
)

Returns_30yr=Returns_30yr/100

x = 1954:2022

frame = data.frame(matrix(ncol=102, nrow=69))
frame[,1] = c(seq(1954,2022))
for(i in 4:104){
  for(j in 29:97){
    z = data[j,i] - Returns_30yr[j-28]
    frame[j-28, i-2] = z/Alpha$Std_29[i-3]}}

  

vect = vector()
for(i in 2:102){
  vect = append(vect, mean(frame[, i]))}


plot(x = 0:100, y = vect, main = "Historic Sharpe Ratio", ylab="Sharpe Ratio", xlab="alpha", type = "l")

# Conditional Expectation of total return given it will be positive
Alpha["E[TR | TR > 0]"]=NA

for(i in 4:104){
  y = data.frame(data[,c(1,i)])
  y = y %>% arrange(y[,2])
  colnames(y) = c(paste0("Date",i-4), paste0(i-4, "/", 104-i))
  y = subset(y, y[,2] > 0)
  Alpha$`E[TR | TR > 0]`[i-3] = mean(y[,2])}


Alpha["E[TR | TR < 0]"]=NA

for(i in 4:104){
  y = data.frame(data[,c(1,i)])
  y = y %>% arrange(y[,2])
  colnames(y) = c(paste0("Date",i-4), paste0(i-4, "/", 104-i))
  y = subset(y, y[,2] < 0)
  Alpha$`E[TR | TR < 0]`[i-3] = mean(y[,2])}


for(i in 4:104){
  y = data.frame(data[,c(1,i)])
  y = y %>% arrange(y[,2])
  colnames(y) = c(paste0("Date",i-4), paste0(i-4, "/", 104-i))
  y = subset(y, y[,2] > 0)
  Alpha$`SD[TR | TR > 0]`[i-3] = sqrt(var(y[,2]))}

for(i in 4:104){
  y = data.frame(data[,c(1,i)])
  y = y %>% arrange(y[,2])
  colnames(y) = c(paste0("Date",i-4), paste0(i-4, "/", 104-i))
  y = subset(y, y[,2] < 0)
  Alpha$`SD[TR | TR < 0]`[i-3] = sqrt(var(y[,2]))}

  
library("plotrix")

Alpha = Alpha %>%
  mutate("Z-Score" = (0 - Alpha$Mean)/Alpha$STD_DEV)

Alpha = Alpha %>%
  mutate("P(TR > 0)" = pnorm(Alpha$`Z-Score`, lower.tail = FALSE))

Alpha = Alpha %>%
  mutate("Z-Score2" = (-0.16 - Alpha$Mean)/Alpha$STD_DEV)

Alpha = Alpha %>%
  mutate("P(TR > -0.16)" = pnorm(Alpha$`Z-Score2`, lower.tail = FALSE))

x = (Alpha$`P(TR > -0.16)`[82] - 0.95)
y = x/Alpha$`P(TR > -0.16)`[83]
y

plot(x = 0:100, y = Alpha$`P(TR > 0)`, type = "l")

plot(x = 0:100, y = Alpha$`P(TR > -0.16)`, type = "l")
abline(h=0.95, col="red")

qnorm(0.95, lower.tail = TRUE)

Alpha["E[TR]"]=NA
for(i in 1:101){
  Alpha$`E[TR]` = (Alpha$`P(TR > 0)`[i] * Alpha$`E[TR | TR > 0]`[i]) + ((1 - Alpha$`P(TR > 0)`[i]) * Alpha$`E[TR | TR < 0]`[i])}

plot(x = 0:100, y = Alpha$`P(TR > 0)`, xlab="Alpha(Large Cap %)", ylab="Probability", main = "Probability Total Returns are Positive")




weighted_TR <- read_excel("Pension Investment Calculation (Annual) MRP600 Sim.xlsx", 
    sheet = "Weighted TR", col_names = FALSE)
vect0 = vector()
for(i in 1:length(colnames(weighted_TR))){
  for(j in 1:length(weighted_TR$...1)){
    vect0 = append(vect0, weighted_TR[j,i])
  }
}
sum = 0
for(i in 1:30000){
  sum = sum + vect0[[i]]}
mean = sum/30000
mean
list1 = list(rep(NA, 30000))
for(i in 1:30000){
  list1[i] = vect0[[i]]}

list1 = data.frame(list1)
list1 = data.frame(t(list1))

sum1 = sum(list1$t.list1.[1:10000])
mean1 = sum1/10000
sd1 = sqrt(var(list1$t.list1.[1:10000]))
diff1 = -0.16-mean1
z_score1 = diff1/sd1
pnorm(z_score1, lower.tail=TRUE)

sd = sqrt(var(list1$t.list1.))
diff = -0.16 - mean 
z_score = diff/sd
pnorm(z_score, lower.tail=TRUE)


Conf = Alpha[c(1,4,5,7:10,12:13)]
Conf = Conf %>%
  mutate("+lower" = Conf$`E[TR | TR > 0]` - 1.96*Conf$`SD[TR | TR > 0]`)

Conf = Conf %>%
  mutate("+upper" = Conf$`E[TR | TR > 0]` + 1.96*Conf$`SD[TR | TR > 0]`)


plotCI(x = 0:100, y = Conf$`E[TR | TR > 0]`, li = Conf$`+lower`, ui = Conf$`+upper`, main="CI Assuming TR > 0", ylab="Total Return", xlab="alpha")
abline(v = 59, col = "red", lty = "dashed")
abline(h = max(Conf$`+lower`), col = "red", lty = "dashed")
mtext("max(lower bound) @ 59", side=3, line = -1, adj = 0.1, cex=.7)

library(ggplot2)

df = data.frame(matrix(ncol=3, nrow=9797))
for(i in 0:100){
  x = i*97 + 1
  y = (1+i)*97
  df[x:y, 1] = data[,i+4]
  df[x:y, 2] = paste0(colnames(data)[i+4])}

Alpha[c("Spread_Ratio", "min", "max")][97:101,]

ggplot2::ggplot(data = df[1:1552,], mapping = aes(x=X1), freq=FALSE) + 
  geom_histogram(binwidth=0.025)+
  geom_density(col="red") +
  scale_x_continuous(name = "Total Returns",
                     breaks = seq(-0.15, 0.35, 0.1),
                     limits=c(-0.15, 0.35)) +
  scale_y_continuous(name = "Frequency") +
  ggtitle("Histograms w/ Varying Alpha") +
  scale_fill_gradient("Count", low = "blue", high = "red") +
  geom_vline(aes(xintercept = mean(df$X1), group = X2), size = 1, colour = "#FF3721",
                   linetype = "dashed") +
  facet_wrap(~X2) + 
  geom_line(aes(y = mean(df$X1)))+
  theme(strip.text = element_text(size = 10),
        axis.text = element_text(size=10),
        strip.background = element_rect())

ggplot2::ggplot(data = df[1553:3104,], mapping = aes(x=X1), freq=FALSE) + 
  geom_histogram(binwidth=0.025)+
  geom_density(col="red") +
  scale_x_continuous(name = "Total Returns",
                     breaks = seq(-0.15, 0.35, 0.1),
                     limits=c(-0.15, 0.35)) +
  scale_y_continuous(name = "Frequency") +
  scale_fill_gradient("Count", low = "blue", high = "red") +
  geom_vline(aes(xintercept = mean(df$X1), group = X2), size = 1, colour = "#FF3721",
                   linetype = "dashed") +
  facet_wrap(~X2) + 
  geom_line(aes(y = mean(df$X1)))+
  theme(strip.text = element_text(size = 10),
        axis.text = element_text(size=10),
        strip.background = element_rect())


ggplot2::ggplot(data = df[3105:4656,], mapping = aes(x=X1), freq=FALSE) + 
  geom_histogram(binwidth=0.025)+
  geom_density(col="red") +
  scale_x_continuous(name = "Total Returns",
                     breaks = seq(-0.25, 0.35, 0.1),
                     limits=c(-0.25, 0.35)) +
  scale_y_continuous(name = "Frequency") +
  scale_fill_gradient("Count", low = "blue", high = "red") +
  geom_vline(aes(xintercept = mean(df$X1), group = X2), size = 1, colour = "#FF3721",
                   linetype = "dashed") +
  facet_wrap(~X2) + 
  geom_line(aes(y = mean(df$X1)))+
  theme(strip.text = element_text(size = 10),
        axis.text = element_text(size=9),
        strip.background = element_rect())

ggplot2::ggplot(data = df[4657:6208,], mapping = aes(x=X1), freq=FALSE) + 
  geom_histogram(binwidth=0.025)+
  geom_density(col="red") +
  scale_x_continuous(name = "Total Returns",
                     breaks = seq(-0.3, 0.4, 0.15),
                     limits=c(-0.3, 0.4)) +
  scale_y_continuous(name = "Frequency") +
  scale_fill_gradient("Count", low = "blue", high = "red") +
  geom_vline(aes(xintercept = mean(df$X1), group = X2), size = 1, colour = "#FF3721",
                   linetype = "dashed") +
  facet_wrap(~X2) + 
  geom_line(aes(y = mean(df$X1)))+
  theme(strip.text = element_text(size = 10),
        axis.text = element_text(size=10),
        strip.background = element_rect())

ggplot2::ggplot(data = df[6209:7760,], mapping = aes(x=X1), freq=FALSE) + 
  geom_histogram(binwidth=0.025)+
  geom_density(col="red") +
  scale_x_continuous(name = "Total Returns",
                     breaks = seq(-0.35, 0.45, 0.15),
                     limits=c(-0.35, 0.45)) +
  scale_y_continuous(name = "Frequency") +
  scale_fill_gradient("Count", low = "blue", high = "red") +
  geom_vline(aes(xintercept = mean(df$X1), group = X2), size = 1, colour = "#FF3721",
                   linetype = "dashed") +
  facet_wrap(~X2) + 
  geom_line(aes(y = mean(df$X1)))+
  theme(strip.text = element_text(size = 10),
        axis.text = element_text(size=10),
        strip.background = element_rect())

ggplot2::ggplot(data = df[7761:9312,], mapping = aes(x=X1), freq=FALSE) + 
  geom_histogram(binwidth=0.05)+
  geom_density(col="red") +
  scale_x_continuous(name = "Total Returns",
                     breaks = seq(-0.45, 0.55, 0.2),
                     limits=c(-0.45, 0.55)) +
  scale_y_continuous(name = "Frequency") +
  scale_fill_gradient("Count", low = "blue", high = "red") +
  geom_vline(aes(xintercept = mean(df$X1), group = X2), size = 1, colour = "#FF3721",
                   linetype = "dashed") +
  facet_wrap(~X2) + 
  geom_line(aes(y = mean(df$X1)))+
  theme(strip.text = element_text(size = 10),
        axis.text = element_text(size=10),
        strip.background = element_rect())

ggplot2::ggplot(data = df[9313:9797,], mapping = aes(x=X1), freq=FALSE) + 
  geom_histogram(binwidth=0.05)+
  geom_density(col="red") +
  scale_x_continuous(name = "Total Returns",
                     breaks = seq(-0.45, 0.55, 0.2),
                     limits=c(-0.45, 0.55)) +
  scale_y_continuous(name = "Frequency") +
  scale_fill_gradient("Count", low = "blue", high = "red") +
  geom_vline(aes(xintercept = mean(df$X1), group = X2), size = 1, colour = "#FF3721",
                   linetype = "dashed") +
  facet_wrap(~X2) + 
  geom_line(aes(y = mean(df$X1)))+
  theme(strip.text = element_text(size = 10),
        axis.text = element_text(size=10),
        strip.background = element_rect())




```




```{r}
library(readxl)
data2 <- read_excel("Project 2 Historical Data.xlsx", 
    range = "A1186:P1283")

colnames(data2) = c("Year",	"Ibbotson® SBBI® US Large-Cap Stocks (Total Return)", "Ibbotson® SBBI® US Large-Cap Stocks (Income Return)",	"Ibbotson® SBBI® US Large-Cap Stocks (Capital Appreciation  Return)",	"Ibbotson® SBBI® US Small-Cap Stocks (Total Return)",	"Ibbotson® SBBI® US Long-term (20-Year) Corporate Bonds (Total Return)",	"Ibbotson® SBBI® US Long-term (20-Year) Government Bonds (Total Return)",	"Ibbotson® SBBI® US Long-term (20-Year) Government Bonds (Income Return)",	"Ibbotson® SBBI® US Long-term (20-Year) Government Bonds (Capital Appreciation Return)",	"Ibbotson® SBBI® US Long-term (20-Year)  Government Bonds (Yield)",	"Ibbotson® SBBI® US Intermediate-term (5-Year) Government Bonds (Total Return)",	"Ibbotson® SBBI® US Intermediate-term (5-Year) Government Bonds (Income Return)",	"Ibbotson® SBBI® US Intermediate-term (5-Year) Government Bonds (Capital Appreciation Return)",	"Ibbotson® SBBI® US Intermediate-term (5-Year) Government Bonds (Yield)",	"Ibbotson® SBBI® US (30-Day) Treasury Bills",	"Ibbotson® SBBI® US Inflation")

data2 = data2[, c(1,2,6,7,11)]

data2["Large_Cap"] = NA
for(i in 1:97){
  data2$Large_Cap[i] = data2$`Ibbotson® SBBI® US Large-Cap Stocks (Total Return)`[i] + data2$`Ibbotson® SBBI® US Long-term (20-Year) Government Bonds (Total Return)`[i]
}
  
data2 = data2 %>%
  mutate("Large_Cap" =data2[,2]+data2[,4])


Conf2 = data.frame(matrix(nrow=97, ncol=102))
colnames(Conf2) = c("Year", colnames(data)[4:104])





for(i in 0:100){
  alpha = i
  alpha=alpha/100
  for(j in 1:97){
    long_corp = (1-alpha) * 0.35 * data2$`Ibbotson® SBBI® US Long-term (20-Year) Corporate Bonds (Total Return)`[j]
    intermediate_gov = (1-alpha) * 0.65 * data2$`Ibbotson® SBBI® US Intermediate-term (5-Year) Government Bonds (Total Return)`[j]
    Large_Cap = alpha * data2$`Ibbotson® SBBI® US Large-Cap Stocks (Total Return)`[j]
    TR = long_corp+intermediate_gov+Large_Cap
    Conf2[j, i+2] = TR}}
Conf2$Year = data2$Year


vect2 = vector()
for(i in 2:102){
  vect2 = append(vect2, mean(Conf2[,i]))}
plot(x=0:100, y = vect2)



data3 = data.frame(matrix(nrow=70, ncol=102))
colnames(data3) = c("Year", colnames(data)[4:104])
data3$Year[1:68] = data$Date[1:68]
data3$Year[69] = "mean(Interest Compounded Annually)"
data3$Year[70] = "sd(Interest Compounded Annually)"
for(i in 4:104){
  for(j in 1:68){
    prod = 1
    y = j+29
    x = data[j:y, i]
    x = x + 1
    for(k in 1:30){
      prod = prod * x[k,1]}
  data3[j,i-2] = prod^(1/30)-1}}

for(i in 2:102){
  x = data3[,i][1:68]
  sum = 0
  for(j in 1:length(x)){
    sum = sum + x[j]}
  mean = sum/68
    data3[69, i] = mean
    data3[70, i] = sqrt(var(x))}

Sharpe_Ratio = data.frame(matrix(nrow=101, ncol = 2))
colnames(Sharpe_Ratio) = c("Alpha", "Sharpe_Ratio")
Sharpe_Ratio[,1] = colnames(data3)[2:102]
for(i in 0:100){
  diff = data3[69, i+2] - .05
  ratio = diff/data3[70, i+2]
  Sharpe_Ratio[i+1, 2] = ratio}




```
